# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'launchApplication.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(867, 722)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = CustomTab(self.centralwidget)
        self.tabWidget.setTabsClosable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.findReplaceWidget = QtWidgets.QDockWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.findReplaceWidget.sizePolicy().hasHeightForWidth())
        self.findReplaceWidget.setSizePolicy(sizePolicy)
        self.findReplaceWidget.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.findReplaceWidget.setObjectName("findReplaceWidget")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.findValue = QtWidgets.QLineEdit(self.dockWidgetContents_3)
        self.findValue.setObjectName("findValue")
        self.horizontalLayout.addWidget(self.findValue)
        self.findButton = QtWidgets.QToolButton(self.dockWidgetContents_3)
        self.findButton.setAutoRaise(True)
        self.findButton.setObjectName("findButton")
        self.horizontalLayout.addWidget(self.findButton)
        self.findPrevButton = QtWidgets.QToolButton(self.dockWidgetContents_3)
        self.findPrevButton.setAutoRaise(True)
        self.findPrevButton.setObjectName("findPrevButton")
        self.horizontalLayout.addWidget(self.findPrevButton)
        self.findAllButton = QtWidgets.QToolButton(self.dockWidgetContents_3)
        self.findAllButton.setAutoRaise(True)
        self.findAllButton.setObjectName("findAllButton")
        self.horizontalLayout.addWidget(self.findAllButton)
        self.caseSensitiveButton = QtWidgets.QToolButton(self.dockWidgetContents_3)
        self.caseSensitiveButton.setObjectName("caseSensitiveButton")
        self.horizontalLayout.addWidget(self.caseSensitiveButton)
        self.highlightButton = QtWidgets.QToolButton(self.dockWidgetContents_3)
        self.highlightButton.setObjectName("highlightButton")
        self.horizontalLayout.addWidget(self.highlightButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.replaceValue = QtWidgets.QLineEdit(self.dockWidgetContents_3)
        self.replaceValue.setObjectName("replaceValue")
        self.horizontalLayout_2.addWidget(self.replaceValue)
        self.replaceButton = QtWidgets.QToolButton(self.dockWidgetContents_3)
        self.replaceButton.setAutoRaise(True)
        self.replaceButton.setObjectName("replaceButton")
        self.horizontalLayout_2.addWidget(self.replaceButton)
        self.replaceAllButton = QtWidgets.QToolButton(self.dockWidgetContents_3)
        self.replaceAllButton.setAutoRaise(True)
        self.replaceAllButton.setObjectName("replaceAllButton")
        self.horizontalLayout_2.addWidget(self.replaceAllButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.findReplaceWidget.setWidget(self.dockWidgetContents_3)
        self.gridLayout.addWidget(self.findReplaceWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 867, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFind = QtWidgets.QMenu(self.menubar)
        self.menuFind.setObjectName("menuFind")
        self.menuWindow = QtWidgets.QMenu(self.menubar)
        self.menuWindow.setObjectName("menuWindow")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.directoryTreeDockWidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directoryTreeDockWidget.sizePolicy().hasHeightForWidth())
        self.directoryTreeDockWidget.setSizePolicy(sizePolicy)
        self.directoryTreeDockWidget.setMinimumSize(QtCore.QSize(324, 297))
        self.directoryTreeDockWidget.setObjectName("directoryTreeDockWidget")
        self.directoryDockWidgetContents = QtWidgets.QWidget()
        self.directoryDockWidgetContents.setObjectName("directoryDockWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.directoryDockWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.directoryTreeView = DirectoryTree(self.directoryDockWidgetContents)
        self.directoryTreeView.setObjectName("directoryTreeView")
        self.gridLayout_2.addWidget(self.directoryTreeView, 0, 0, 1, 1)
        self.directoryTreeDockWidget.setWidget(self.directoryDockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.directoryTreeDockWidget)
        self.interpreterDockWidget = QtWidgets.QDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interpreterDockWidget.sizePolicy().hasHeightForWidth())
        self.interpreterDockWidget.setSizePolicy(sizePolicy)
        self.interpreterDockWidget.setMinimumSize(QtCore.QSize(105, 259))
        self.interpreterDockWidget.setMaximumSize(QtCore.QSize(524287, 800))
        self.interpreterDockWidget.setObjectName("interpreterDockWidget")
        self.interpreterDockWidgetContents = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interpreterDockWidgetContents.sizePolicy().hasHeightForWidth())
        self.interpreterDockWidgetContents.setSizePolicy(sizePolicy)
        self.interpreterDockWidgetContents.setMaximumSize(QtCore.QSize(16777215, 800))
        self.interpreterDockWidgetContents.setObjectName("interpreterDockWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.interpreterDockWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.interpreterWidget = EmbedIPython(self.interpreterDockWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.interpreterWidget.sizePolicy().hasHeightForWidth())
        self.interpreterWidget.setSizePolicy(sizePolicy)
        self.interpreterWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.interpreterWidget.setMaximumSize(QtCore.QSize(16777215, 800))
        self.interpreterWidget.setObjectName("interpreterWidget")
        self.gridLayout_4.addWidget(self.interpreterWidget, 0, 0, 1, 1)
        self.interpreterDockWidget.setWidget(self.interpreterDockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.interpreterDockWidget)
        self.actionCtrl_N = QtWidgets.QAction(MainWindow)
        self.actionCtrl_N.setObjectName("actionCtrl_N")
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionCloseTab = QtWidgets.QAction(MainWindow)
        self.actionCloseTab.setObjectName("actionCloseTab")
        self.actionCloseAllTab = QtWidgets.QAction(MainWindow)
        self.actionCloseAllTab.setObjectName("actionCloseAllTab")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaveAs = QtWidgets.QAction(MainWindow)
        self.actionSaveAs.setObjectName("actionSaveAs")
        self.actionRecent = QtWidgets.QAction(MainWindow)
        self.actionRecent.setObjectName("actionRecent")
        self.actionCut = QtWidgets.QAction(MainWindow)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        self.actionPaste.setObjectName("actionPaste")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionIndent = QtWidgets.QAction(MainWindow)
        self.actionIndent.setObjectName("actionIndent")
        self.actionUnIndent = QtWidgets.QAction(MainWindow)
        self.actionUnIndent.setObjectName("actionUnIndent")
        self.actionLineCut = QtWidgets.QAction(MainWindow)
        self.actionLineCut.setObjectName("actionLineCut")
        self.actionLineCopy = QtWidgets.QAction(MainWindow)
        self.actionLineCopy.setObjectName("actionLineCopy")
        self.actionLinePaste = QtWidgets.QAction(MainWindow)
        self.actionLinePaste.setObjectName("actionLinePaste")
        self.actionLineDuplicate = QtWidgets.QAction(MainWindow)
        self.actionLineDuplicate.setObjectName("actionLineDuplicate")
        self.actionLineTranspose = QtWidgets.QAction(MainWindow)
        self.actionLineTranspose.setObjectName("actionLineTranspose")
        self.actionCommentUncomment = QtWidgets.QAction(MainWindow)
        self.actionCommentUncomment.setObjectName("actionCommentUncomment")
        self.actionGotoLine = QtWidgets.QAction(MainWindow)
        self.actionGotoLine.setObjectName("actionGotoLine")
        self.actionHighlight = QtWidgets.QAction(MainWindow)
        self.actionHighlight.setObjectName("actionHighlight")
        self.actionUpperCase = QtWidgets.QAction(MainWindow)
        self.actionUpperCase.setObjectName("actionUpperCase")
        self.actionLowerCase = QtWidgets.QAction(MainWindow)
        self.actionLowerCase.setObjectName("actionLowerCase")
        self.actionCamelCase = QtWidgets.QAction(MainWindow)
        self.actionCamelCase.setObjectName("actionCamelCase")
        self.actionFind = QtWidgets.QAction(MainWindow)
        self.actionFind.setObjectName("actionFind")
        self.actionFindAll = QtWidgets.QAction(MainWindow)
        self.actionFindAll.setObjectName("actionFindAll")
        self.actionReplace = QtWidgets.QAction(MainWindow)
        self.actionReplace.setObjectName("actionReplace")
        self.actionReplaceAll = QtWidgets.QAction(MainWindow)
        self.actionReplaceAll.setObjectName("actionReplaceAll")
        self.actionLineMove = QtWidgets.QAction(MainWindow)
        self.actionLineMove.setObjectName("actionLineMove")
        self.actionLineDown = QtWidgets.QAction(MainWindow)
        self.actionLineDown.setObjectName("actionLineDown")
        self.actionFoldAll = QtWidgets.QAction(MainWindow)
        self.actionFoldAll.setObjectName("actionFoldAll")
        self.actionOpenDirectory = QtWidgets.QAction(MainWindow)
        self.actionOpenDirectory.setObjectName("actionOpenDirectory")
        self.actionPythonInterpreter = QtWidgets.QAction(MainWindow)
        self.actionPythonInterpreter.setObjectName("actionPythonInterpreter")
        self.actionFoldCurrent = QtWidgets.QAction(MainWindow)
        self.actionFoldCurrent.setObjectName("actionFoldCurrent")
        self.actionClearFoldings = QtWidgets.QAction(MainWindow)
        self.actionClearFoldings.setObjectName("actionClearFoldings")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpenDirectory)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionRecent)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaveAs)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionCloseTab)
        self.menuFile.addAction(self.actionCloseAllTab)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionIndent)
        self.menuEdit.addAction(self.actionUnIndent)
        self.menuEdit.addAction(self.actionLineCut)
        self.menuEdit.addAction(self.actionLineCopy)
        self.menuEdit.addAction(self.actionLineMove)
        self.menuEdit.addAction(self.actionLineTranspose)
        self.menuEdit.addAction(self.actionLineDuplicate)
        self.menuEdit.addAction(self.actionCommentUncomment)
        self.menuEdit.addAction(self.actionLineDown)
        self.menuEdit.addAction(self.actionFoldAll)
        self.menuEdit.addAction(self.actionFoldCurrent)
        self.menuEdit.addAction(self.actionClearFoldings)
        self.menuFind.addAction(self.actionFind)
        self.menuFind.addAction(self.actionFindAll)
        self.menuFind.addAction(self.actionReplace)
        self.menuFind.addAction(self.actionReplaceAll)
        self.menuFind.addAction(self.actionGotoLine)
        self.menuFind.addAction(self.actionHighlight)
        self.menuFind.addAction(self.actionUpperCase)
        self.menuFind.addAction(self.actionLowerCase)
        self.menuFind.addAction(self.actionCamelCase)
        self.menuWindow.addAction(self.actionPythonInterpreter)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuFind.menuAction())
        self.menubar.addAction(self.menuWindow.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.findButton.setText(_translate("MainWindow", "Find"))
        self.findPrevButton.setText(_translate("MainWindow", "Find Prev"))
        self.findAllButton.setText(_translate("MainWindow", "Find All"))
        self.caseSensitiveButton.setText(_translate("MainWindow", "..."))
        self.highlightButton.setText(_translate("MainWindow", "..."))
        self.replaceButton.setText(_translate("MainWindow", "Replace"))
        self.replaceAllButton.setText(_translate("MainWindow", "Replace All"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuFind.setTitle(_translate("MainWindow", "Find"))
        self.menuWindow.setTitle(_translate("MainWindow", "Window"))
        self.actionCtrl_N.setText(_translate("MainWindow", "Ctrl+N"))
        self.actionNew.setText(_translate("MainWindow", "New                Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open File        Ctrl+O"))
        self.actionExit.setText(_translate("MainWindow", "Exit                  Alt+F4"))
        self.actionCloseTab.setText(_translate("MainWindow", "Close Tab        Ctrl+W"))
        self.actionCloseAllTab.setText(_translate("MainWindow", "Close All Tab"))
        self.actionSave.setText(_translate("MainWindow", "Save                Ctrl+S"))
        self.actionSaveAs.setText(_translate("MainWindow", "Save As"))
        self.actionRecent.setText(_translate("MainWindow", "Recent"))
        self.actionCut.setText(_translate("MainWindow", "Cut                     Ctrl+X"))
        self.actionCopy.setText(_translate("MainWindow", "Copy                  Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Paste                  Ctrl+V"))
        self.actionUndo.setText(_translate("MainWindow", "Undo                 Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo                  Ctrl+Y"))
        self.actionIndent.setText(_translate("MainWindow", "Indent                Tab"))
        self.actionUnIndent.setText(_translate("MainWindow", "UnIndent            Shift+Tab"))
        self.actionLineCut.setText(_translate("MainWindow", "Line Cut              Ctrl+L"))
        self.actionLineCopy.setText(_translate("MainWindow", "Line Copy           Ctrl+Shift+T"))
        self.actionLinePaste.setText(_translate("MainWindow", "Line Paste           Ctrl+Shift+L"))
        self.actionLineDuplicate.setText(_translate("MainWindow", "Line Duplicate    Ctrl+D"))
        self.actionLineTranspose.setText(_translate("MainWindow", "Line Transpose   Ctrl+T"))
        self.actionCommentUncomment.setText(_translate("MainWindow", "Un/comment     Ctrl+/"))
        self.actionGotoLine.setText(_translate("MainWindow", "Goto Line        Ctrl+G"))
        self.actionHighlight.setText(_translate("MainWindow", "Highlight        Ctrl+M"))
        self.actionUpperCase.setText(_translate("MainWindow", "UpperCase       Alt+U"))
        self.actionLowerCase.setText(_translate("MainWindow", "LowerCase      Alt+L"))
        self.actionCamelCase.setText(_translate("MainWindow", "CamelCase     Alt+C"))
        self.actionFind.setText(_translate("MainWindow", "Find             Ctrl+F"))
        self.actionFindAll.setText(_translate("MainWindow", "Find All     Ctrl+Shift+F"))
        self.actionReplace.setText(_translate("MainWindow", "Replace        Ctrl+R"))
        self.actionReplaceAll.setText(_translate("MainWindow", "Replace All      Ctrl+Shift+R"))
        self.actionLineMove.setText(_translate("MainWindow", "Line Move          Ctrl+Shift+U"))
        self.actionLineDown.setText(_translate("MainWindow", "Line Down         Ctrl+Shift+d"))
        self.actionFoldAll.setText(_translate("MainWindow", "Fold All              Alt+F"))
        self.actionOpenDirectory.setText(_translate("MainWindow", "Open Directory"))
        self.actionPythonInterpreter.setText(_translate("MainWindow", "Python Interpreter"))
        self.actionFoldCurrent.setText(_translate("MainWindow", "Fold Current      Alt+C"))
        self.actionClearFoldings.setText(_translate("MainWindow", "Clear Foldings   Alt+Z"))

from _widgets.directoryTreeWidget import DirectoryTree
from _widgets.interpreterWidget import EmbedIPython
from _widgets.scintillaEditor import CustomTab

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

